# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'FirebaseDatabase'
  pod 'Firebase/Storage'
  pod 'Firebase/Crash'
  pod 'RealmSwift'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  # Pods for Task

end
